services:
  webserver:
    # docker login --username=taohongmin@sina.cn crpi-70qzhn1dtv3eo91r.cn-hangzhou.personal.cr.aliyuncs.com
    # 需要先登录，密码为：大写字母 + 小写字母 + 6位数字
    image: crpi-70qzhn1dtv3eo91r.cn-hangzhou.personal.cr.aliyuncs.com/taohongmin/obfuscate:latest
    volumes:
      - /www/wwwroot/obf.jcaigc.cn:/app/output  # 挂载配置文件目录
      - /etc/localtime:/etc/localtime:ro  # 挂载主机时区
      - /etc/timezone:/etc/timezone:ro    # 挂载时区名称（可选）
    mem_limit: 1.0G   # 内存限制
    memswap_limit: 2G # 总内存（物理内存 + Swap）限制
    cpus: '1.0'       # CPU使用率限制为150%，即容器最多可以使用1.5个完整的CPU核心
    oom_score_adj: -500  # 调整 OOM 杀手优先级
    container_name: obfuscate # 这里指容器名称，非必需，不指定时，名称为：<项目名称>-<服务名称>-<序号>
    #entrypoint: ["/bin/sh", "-c", "sleep 10000"]