name: Build And Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build And Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 先安装 pnpm
      - name: 安装 pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10   # 明确指定 pnpm 大版本 (推荐)

      # 再设置 Node.js 环境
      - name: 设置node js环境
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: 安装依赖
        run: pnpm install

      - name: 缓存清理
        run: pnpm run clean || true

      - name: 编译
        run: pnpm run build

      - name: 检查编译结果
        run: ls -lhR ./dist

      - name: 打包前准备
        run: |
          mkdir -p PACKAGE/app/bin
          mkdir -p PACKAGE/app/etc
          cp -rf ./dist/* PACKAGE/app/bin/
          # 写入commit hash到文件中
          echo "${{ github.sha }}" > PACKAGE/app/etc/commit_hash

      - name: 打包docker镜像
        run: docker build . --tag obfuscate:${{ github.sha }}

      - name: 登录到阿里云容器镜像服务器
        run: echo "${{ secrets.ALIYUN_ACR_PASSWORD }}" | docker login -u ${{ secrets.ALIYUN_ACR_USERNAME }} --password-stdin crpi-70qzhn1dtv3eo91r.cn-hangzhou.personal.cr.aliyuncs.com
      
      - name: 给docker镜像打latest的tag
        run: docker tag obfuscate:${{ github.sha }} crpi-70qzhn1dtv3eo91r.cn-hangzhou.personal.cr.aliyuncs.com/taohongmin/obfuscate:latest
      
      - name: 推送docker镜像到阿里云容器镜像服务器
        run: docker push crpi-70qzhn1dtv3eo91r.cn-hangzhou.personal.cr.aliyuncs.com/taohongmin/obfuscate:latest

      - name: 给docker镜像打commit hash的tag
        run: docker tag obfuscate:${{ github.sha }} crpi-70qzhn1dtv3eo91r.cn-hangzhou.personal.cr.aliyuncs.com/taohongmin/obfuscate:${{ github.sha }}
      
      - name: 推送docker镜像到阿里云容器镜像服务器
        run: docker push crpi-70qzhn1dtv3eo91r.cn-hangzhou.personal.cr.aliyuncs.com/taohongmin/obfuscate:${{ github.sha }}
      
  notify:
    name: Send Notify
    runs-on: ubuntu-latest
    needs: build
    if: always()  # 无论工作流是成功还是失败都发送邮件
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: ${{ github.repository }} 打包结果：${{ needs.build.result }}
          body: |           
            Workflow: ${{ github.workflow }}
            Repository: ${{ github.repository }}
            Build Result: ${{ needs.build.result }}
            GitHub Sha: ${{ github.sha }}
            GitHub Release: ${{ github.ref_name }}
          to: taohongmin@sina.cn, gogoshine168@gmail.com
          from: 229566369@qq.com